language: node_js
dist: bionic
os:
  - osx
  - windows
node_js: "12"
env:
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
  - YARN_GPG=no
script:
  - yarn build --publish
