import SeratoTrackSerializer from "./SeratoTrackSerializer"

const testId3Tags = {
  'Serato Analysis': 'R0VPQgAAAC0AAABhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0AAFNlcmF0byBBbmFseXNpcwACAQ==',
  'Serato Autotags': 'R0VPQgAAAEAAAABhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0AAFNlcmF0byBBdXRvdGFncwABATg1LjAwAC0xLjE0NQAwLjAwMAA=',
  'Serato BeatGrid': 'R0VPQgAAADoAAABhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0AAFNlcmF0byBCZWF0R3JpZAABAAAAAAE/8TAXQqoAADI=',
  'Serato Markers2': 'R0VPQgAAAgEAAABhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0AAFNlcmF0byBNYXJrZXJzMgABAUFRRkRUMHhQVWdBQUFBQUVBUC8vLzBOVlJRQUFBQUFOQUFFQUFFSkpBTXlJQUFBQUFFTlZSUUFBQUFBTkFBTUFBZnFjQU16TQpBQUFBQUVKUVRVeFBRMHNBQUFBQUFRQUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  'Serato Markers_': 'R0VPQgAAAWkAAABhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0AAFNlcmF0byBNYXJrZXJzXwACBQAAAA5/f39/f39/f39/AH9/f39/AAAAAAAAAAABBEl/f39/fwB/f39/fwYyEAABAH9/f39/f39/f38Af39/f38AAAAAAAAAAAd1HH9/f39/AH9/f39/BjMYAAEAf39/f39/f39/fwB/f39/fwAAAAAAAH9/f39/f39/f38Af39/f38AAAAAAwB/f39/f39/f39/AH9/f39/AAAAAAMAf39/f39/f39/fwB/f39/fwAAAAADAH9/f39/f39/f38Af39/f38AAAAAAwB/f39/f39/f39/AH9/f39/AAAAAAMAf39/f39/f39/fwB/f39/fwAAAAADAH9/f39/f39/f38Af39/f38AAAAAAwB/f39/f39/f39/AH9/f39/AAAAAAMAf39/f39/f39/fwB/f39/fwAAAAADAAd/f38=',
  /* 'Serato Offsets_': '...', */
  /* 'Serato Overview': '...', */
}

const testFlacTag = {
  SERATO_ANALYSIS: [ 'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gQW5hbHlzaXMAAgEA' ],
  SERATO_AUTOGAIN: [
    'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gQXV0b3RhZ3MAAQE4Ny41MAAtNi44\n' +
      'MjEAMC4wMDAAA'
  ],
  SERATO_BEATGRID: [
    'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gQmVhdEdyaWQAAQAAAAABAAAAAEKv\n' +
      'AACgA'
  ],
  SERATO_MARKERS_V2: [
    'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAQFBUUZEVDB4UFVn\n' +
      'QUFBQUFFQVAvLy8wTlZSUUFBQUFBTkFBQUFBQlZxQU13QUFBQUFBRU5WUlFBQUFBQU5BQUVB\n' +
      'QWt0T0FBQUEKekFBQUFFSlFUVXhQUTBzQUFBQUFBUUFBAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' +
      'AAAAAAAAAAAAAAAAAAAAAA'
  ],
  // SERATO_OVERVIEW: ommitted
  SERATO_PLAYCOUNT: [ '2' ],
  SERATO_RELVOL: [
    'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gUmVsVm9sQWQAAQEBAAAA'
  ],
  SERATO_VIDEO_ASSOC: [
    'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gVmlkQXNzb2MAAQEBAAAA'
  ],
}

const serializer = new SeratoTrackSerializer()

test('should deserialize track info from ID3', () => {
  const geobTags = [...Object.values(testId3Tags)]
    .reduce((obj, t, index) => ({ ...obj, [index]: Buffer.from(t, 'base64').slice(11) }), {})
  const trackInfo = serializer.deserialize(geobTags)

  expect(trackInfo.cues).toMatchObject([
    { index: 1, color: '#cc8800', milliseconds: 16969 },
    { index: 3, color: '#cccc00', milliseconds: 129692 },
  ])
})

test('should deserialize track info from FLAC', () => {
  const geobTags = [
    testFlacTag['SERATO_ANALYSIS'],
    testFlacTag['SERATO_AUTOGAIN'],
    testFlacTag['SERATO_BEATGRID'],
    testFlacTag['SERATO_MARKERS_V2'],
    testFlacTag['SERATO_RELVOL'],
    testFlacTag['SERATO_VIDEO_ASSOC'],
  ].reduce((obj, t, index) => ({ ...obj, [index]: Buffer.from(t[0], 'base64') }), {})
  const trackInfo = serializer.deserialize(geobTags)

  expect(trackInfo.cues).toMatchObject([
    { index: 0, color: '#cc0000', milliseconds: 5482 },
    { index: 1, color: '#0000cc', milliseconds: 150350 },
  ])
})

test('should serialize track info', () => {
  const cues = [
    { index: 0, color: '#cc0000', milliseconds: 5482 },
    { index: 1, color: '#0000cc', milliseconds: 150350 },
  ]
  const map = serializer.serialize({ cues })

  // TODO add BPM Lock and other frames
  const expected = 'YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAABBUUZEVlVVQUFBQUFEUUFBQUFBVmFnRE1BQUFBQUFCRFZVVUFBQUFBRFFBQkFBSkxUZ0FBQU13QUFBQUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
  expect(map['Serato Markers2'].toString('base64')).toBe(expected)
})
